"use client";

import { useState } from "react";
import { Download, Loader2, Navigation, Truck, CheckCircle2, Clock, Package } from "lucide-react";
import { adminGenerateInvoiceAction } from "@/app/actions/shiprocket";

interface CustomerOrderTrackingProps {
  orderId: string;
  invoiceUrl?: string;
  awbCode?: string;
  carrier: string;
  trackingData?: any;
  status: string;
}

export function CustomerOrderTracking({
  orderId,
  invoiceUrl: initialInvoiceUrl,
  awbCode,
  carrier,
  trackingData,
  status,
}: CustomerOrderTrackingProps) {
  const [downloadingInvoice, setDownloadingInvoice] = useState(false);
  const [invoiceUrl, setInvoiceUrl] = useState(initialInvoiceUrl);

  const handleDownloadInvoice = async () => {
    if (invoiceUrl) {
      window.open(invoiceUrl, "_blank");
      return;
    }

    setDownloadingInvoice(true);
    try {
      const res = await adminGenerateInvoiceAction(orderId);
      if (res.success && res.invoiceUrl) {
        setInvoiceUrl(res.invoiceUrl);
        window.open(res.invoiceUrl, "_blank");
      } else {
        alert(res.error || "Invoice is being generated by logistics team. Please try again shortly.");
      }
    } catch (e: any) {
      alert(e.message || "Failed to download invoice.");
    } finally {
      setDownloadingInvoice(false);
    }
  };

  const activities = trackingData?.shipment_track_activities || [];
  const isDelivered = status === "DELIVERED";
  const isShipped = status === "SHIPPED" || isDelivered;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <button
          onClick={handleDownloadInvoice}
          disabled={downloadingInvoice}
          className="px-5 py-2.5 rounded-full bg-slate-900 hover:bg-slate-800 text-white type-button flex items-center gap-2 shadow-md cursor-pointer transition-all disabled:opacity-50 text-xs font-mono font-bold"
        >
          {downloadingInvoice ? (
            <Loader2 className="w-4 h-4 animate-spin text-sky-400" />
          ) : (
            <Download className="w-4 h-4 text-sky-400" />
          )}
          <span>Download Tax Invoice (PDF)</span>
        </button>
      </div>

      {/* Live Carrier Scan Activities (if available from Shiprocket) */}
      {activities.length > 0 && (
        <div className="p-5 rounded-2xl bg-blue-50/50 border border-blue-200/80 space-y-4">
          <div className="flex items-center justify-between border-b border-blue-200/60 pb-3">
            <div className="flex items-center gap-2">
              <Navigation className="w-4 h-4 text-blue-600" />
              <h3 className="font-mono font-bold text-xs uppercase text-blue-900">
                Shiprocket Live Carrier Checkpoints ({carrier})
              </h3>
            </div>
            {awbCode && (
              <span className="text-[11px] font-mono text-blue-800 bg-blue-100 px-2.5 py-0.5 rounded-full font-bold">
                AWB: {awbCode}
              </span>
            )}
          </div>

          <div className="space-y-3 border-l-2 border-blue-500 ml-2 pl-4">
            {activities.map((act: any, i: number) => (
              <div key={i} className="relative text-xs space-y-0.5">
                <div className="absolute -left-[21px] top-1 w-2.5 h-2.5 rounded-full bg-blue-600" />
                <div className="font-bold text-slate-900">{act.activity}</div>
                <div className="text-[11px] text-slate-500 font-mono">
                  {act.location ? `${act.location} • ` : ""}{act.date}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
