import sanitizeHtml from "sanitize-html";

/**
 * HTML sanitization options strictly calibrated for rich-text descriptions.
 * Preserves legitimate formatting generated by WixRichTextEditor while stripping
 * all script execution, event handler, iframe, object, and CSS-injection attack vectors.
 */
const ALLOWED_TAGS = [
  // Text formatting
  "p", "br", "b", "strong", "i", "em", "u", "s", "strike", "del", "sub", "sup",
  // Headings
  "h1", "h2", "h3", "h4", "h5", "h6",
  // Lists
  "ul", "ol", "li",
  // Structural & code blocks
  "span", "div", "blockquote", "code", "pre", "hr",
  // Media & links
  "a", "img",
  // Tables
  "table", "thead", "tbody", "tfoot", "tr", "th", "td", "caption", "colgroup", "col",
];

const ALLOWED_ATTRIBUTES: sanitizeHtml.IOptions["allowedAttributes"] = {
  a: ["href", "name", "target", "rel", "title"],
  img: ["src", "alt", "title", "width", "height", "loading"],
  "*": ["style", "class"],
};

const ALLOWED_STYLES: sanitizeHtml.IOptions["allowedStyles"] = {
  "*": {
    color: [
      /^#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/,
      /^rgb\(\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*\d{1,3}\s*\)$/i,
      /^rgba\(\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*(?:0|1|0?\.\d+)\)$/i,
      /^[a-zA-Z]+$/,
    ],
    "background-color": [
      /^#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/,
      /^rgb\(\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*\d{1,3}\s*\)$/i,
      /^rgba\(\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*(?:0|1|0?\.\d+)\)$/i,
      /^[a-zA-Z]+$/,
    ],
    "text-align": [/^(left|right|center|justify)$/i],
    "font-size": [/^\d+(?:\.\d+)?(?:px|em|rem|pt|%)$/i],
    "font-weight": [/^(bold|normal|[1-9]00)$/i],
    "text-decoration": [/^(underline|line-through|none)$/i],
  },
};

const SANITIZE_OPTIONS: sanitizeHtml.IOptions = {
  allowedTags: ALLOWED_TAGS,
  allowedAttributes: ALLOWED_ATTRIBUTES,
  allowedStyles: ALLOWED_STYLES,
  allowedSchemes: ["http", "https", "mailto"],
  allowedSchemesByTag: {
    a: ["http", "https", "mailto"],
    img: ["http", "https"],
  },
  transformTags: {
    a: (tagName, attribs) => {
      const newAttribs = { ...attribs };
      if (newAttribs.target === "_blank" || !newAttribs.rel) {
        newAttribs.rel = "noopener noreferrer";
      }
      return { tagName, attribs: newAttribs };
    },
  },
  // Ensure script, iframe, and other non-text tags have their entire contents removed
  nonTextTags: ["script", "style", "textarea", "option", "noscript", "iframe", "object", "embed", "svg", "math"],
};

/**
 * Sanitize rich-text HTML (e.g., product descriptions, section contents).
 * Strips all malicious scripts, event handlers, and unsafe styles while preserving
 * WixRichTextEditor formatting.
 */
export function sanitizeRichHtml(dirtyHtml?: string | null): string {
  if (!dirtyHtml || typeof dirtyHtml !== "string") {
    return "";
  }
  const trimmed = dirtyHtml.trim();
  if (!trimmed) {
    return "";
  }
  return sanitizeHtml(trimmed, SANITIZE_OPTIONS);
}

export { isSafeUrl, sanitizeUrl } from "./url-sanitizer";

/**
 * Safely serialize data into JSON for inclusion inside <script type="application/ld+json">.
 * Escapes <, >, and & characters to Unicode escapes to prevent </script> tag breakout attacks.
 */
export function safeJsonLdStringify(data: unknown): string {
  return JSON.stringify(data)
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e")
    .replace(/&/g, "\\u0026");
}
